# Site settings
title: GMmario's blog
description: "A blog about MintNetwork ..."
# User settings
username: GMmario
user_title: GMmario - MintNetwork Developer
email: pkmin0422@naver.com/
twitter_username: 
github_username:  GMmario
gplus_username:  
linkedin_public_url: 
disqus_username: 
profile_picture: https://78.media.tumblr.com/a2f63aa1e708bb7e48f543183176ae20/tumblr_oz3lwbcLdJ1wuzsgso1_1280.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: asciilang
    url: https://github.com/victorvoid/asciilang
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
